# mlp_variation_comparison.yaml
---
# parameter_groups: define sets of overrides to apply on top of base params
parameter_groups:
  # Standard MLP - baseline sizes
  - mlp_variant: ["mlp"]
    mlp_size: [768, 1024, 1536]

  # Swiglu - ~2/3 of MLP sizes for same param count
  - mlp_variant: ["swiglu"]
    mlp_size: [512, 683, 1024]

  # DualPath - ~2/3 of MLP sizes for same param count
  - mlp_variant: ["dual_path"]
    mlp_size: [512, 683, 1024]

# base hyperparameters
block_size: [256]
n_layer: [6]
n_head: [6]
n_embd: [384]

# training configuration
batch_size: [64]
gradient_accumulation_steps: [1]
eval_interval: [10000]
eta_variant: ["iteration"]

# compilation
compile: [true]

# training configuration
learning_rate: [6e-4]
min_lr: [6e-5]
max_iters: [10000]
lr_decay_iters: [10000]
warmup_iters: [100]
decay_lr: [true]

# dataset configuration
dataset: ["minipile"]

# dtype
dtype: ["float16", "bfloat16"]
